- name: install cron job (ansible-pull)
  cron:
    user: ansible
    name: "ansible provision"
    day: "*"
    job: "/usr/bin/ansible-pull -o -U https://github.com/cilufarag/ansible_pull.git > /dev/null"
